### ISSUE TITLE
Trying to spawn remoteDefenders with body of 0 when no defender is needed.

### ISSUE THREAD

**Issue by Allorrian** [CarsonBurke/The-Internationale-Screeps-Bot#104]
All rooms besides the keeper in [this](https://media.discordapp.net/attachments/978303053444829217/1000402185760297010/unknown.png?width=810&height=452) are my remotes or communes except the keeper (obviously), and the room directly below it. Yet I see [this](https://media.discordapp.net/attachments/978303053444829217/1000402533694574682/unknown.png?width=810&height=128) in the console while there are no enemies in any of my rooms. This was after a breaking upgrade, is the code possibly seeing there should be active remoteHarvesters and they haven't been spawned yet?

**Comment by CarsonBurke** [comment]
I can't seem to reproduce this :/

**Comment by CarsonBurke** [comment]
This seems to have been fixed
