### ISSUE TITLE
Remote room defenders not spawning

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#15]
![image](https://user-images.githubusercontent.com/45623682/171614220-a19d3b9a-17c8-48fa-a2c1-158b779c77a4.png)
![image](https://user-images.githubusercontent.com/45623682/171614244-148cf74f-7cfa-4cc6-bbb6-b4c0406235f1.png)

Remote isnt being defended, keeps sending normal creeps instead of defenders

**Comment by CarsonBurke** [comment]
It's likely that the remote was abandoned because the bot can't spawn a defender large enough to counter the attack.

It should say if it were abandoned in room memory and map visuals.
