### ISSUE TITLE
Fix fastFillers not withdrawing wrong resources

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#153]
![4882FFBB-1507-4631-BA63-082FEED50383](https://user-images.githubusercontent.com/48334001/183438700-2689e7cf-3dfd-4f98-86b8-dc6a9c83f79a.jpeg)

**Comment by pieterbrandsen** [comment]
Add an forced resource in the withdraw process, this way it cant withdraw other resources. 

Do maybe aswell checks if wrong resource in container, then create task to dispose of it.

**Comment by CarsonBurke** [comment]
It already has code to do this, it just wasn't working. I made some small changes that I think have fixed it but it's hard to test as minerals rarely land on fastFiller containers

**Comment by CarsonBurke** [comment]
I guess I can temporarily adjust mineral harvester code to test
