### ISSUE TITLE
while mineralcount > mincount, create unecessary sell orders that drain your credits

### ISSUE THREAD

**Issue by DefaultO** [CarsonBurke/The-Internationale-Screeps-Bot#154]
![image](https://user-images.githubusercontent.com/42414542/183670788-a32c14f6-4f9c-4cb7-87ed-6488691e56e7.png)

It feels like commie bot creates a sell order for the mineral whenever it is over a specific count. No further checks are in place to stop it from continuously doing it if a selling order for it already exists. Making you repay the market fee for the unchanged selling order every single time it creates the same sell order. Leaving you with no credits and like a hundred active sell orders.

**Comment by pieterbrandsen** [comment]
Luckely it doesnt drain it because if after 30 days the market fee that is left gets paid back but I had this one time aswell.

**Comment by CarsonBurke** [comment]
Finally fixed!
