### ISSUE TITLE
Extractor creep is spawned when prio is low and room is not ready

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#18]
![image](https://user-images.githubusercontent.com/45623682/172072833-c13a929b-7361-4859-92e2-a64b2d5fa2b1.png)
Please check conditions and make the spawn prio lower.

**Comment by CarsonBurke** [comment]
Thanks! I'll review the spawning code and fix this.

**Comment by CarsonBurke** [comment]
![image](https://user-images.githubusercontent.com/48334001/172075657-f4921fbc-a7f2-4639-85fe-cbbc88130a51.png)
I think that creep is from your old bot, not the current one.

**Comment by pieterbrandsen** [comment]
I remembered something, I did have extractor code but I never used it because I got no base planning
