### ISSUE TITLE
Bug - Bot Claiming known allyRemotes as communes

### ISSUE THREAD

**Issue by Allorrian** [CarsonBurke/The-Internationale-Screeps-Bot#180]
**Describe the bug**
Bot is claiming rooms it knows to be an allyRemote as it's own commune 

**Expected behaviour**
Bot should ignore Ally rooms when determining claim targets

**Reproduction**
Would need allies in close proximity to get the rooms to be claimed.

**Media**
![image](https://media.discordapp.net/attachments/1008726598817677352/1011245266222993479/unknown.png)

**Comment by CarsonBurke** [comment]
Thanks! fixed
