### ISSUE TITLE
Dancing from one room to the other Bug

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#183]
**Describe the bug**
When creep is going to another room it keeps coming back and forth

**Expected behaviour**
Should go from one to other without delay

**Reproduction**
Uncertain, saw it when creep was going from remote to another remote

**Potential fix**
-

**Media**
![image](https://user-images.githubusercontent.com/45623682/186107027-1d898ac1-099a-43e2-b9ba-193bb39cafc9.png)

**Comment by CarsonBurke** [comment]
Duplicate issue
