### ISSUE TITLE
creepsFromRoomAmount stat

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#191]
**Describe what you want the bot to do**

A commune-only room stat for creepsFromRoomAmount, to track how many creeps each commune is spawning and utilizing

**Comment by pieterbrandsen** [comment]
Change will be removing **remote creep count** and creating an new stat called **total creep count** which uses creepsFromRoomAmount

**Comment by pieterbrandsen** [comment]
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/commit/9a76eeadd671f5da42c7c33bc1d07fb9f6114d72
