### ISSUE TITLE
Base planning refactor

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#196]
**Describe what you want the bot to do**

- BasePlanner class instantiated that contains methods that handle main aspects of base planning
- RampartPlanner class that handles rampart planning
- Stamp rotation
- Multiple attempts at planning each stamp to see which scores best
- Stamp anchors recorded in memory, separate from everything else and not to be used for structure placement purposes
- Planned structures stored in memory
  - structured as { [key: string (packedCoord)]: } string[] } where each string property is made up of <string (packed structure constant), minimum RCL>[]
- Planned structures stored in memory as string[] where string is String<structureNumberReference, minRCL>
- coordMaps used while planning that persist in room global until deleted when planning is finished
- Abstractor function to read and add to these coordMaps to make things easier
- coordMaps are maps with keys of packed coord strings, values of stringified array informing structures at the tile, and the RCL to build them. They are converted into the planned structures mentioned above when planning is completed
  - structured as Map<string (packedCoord), string[]> where each string property is the same as the aforementioned planned structures

**Comment by pieterbrandsen** [comment]
https://app.milanote.com/1OvVNL1GdZWSaH?p=WfgX7OwiJdg
Some interesting concepts I added is priority structures and max csCount per room
