### ISSUE TITLE
Spawning using disabled structures bug

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#214]
**Describe the bug**
Spawning was trying to use disabled structures

**Expected behaviour**
Spawn max based on non disabled structures

**How can we reproduce this?**
Let an room downgrade and kill all creeps

**Potential fix**
Filter disabled structures out

**Applicable media**

**Comment by CarsonBurke** [comment]
Mostly fixed
