### ISSUE TITLE
File system improvement

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#217]
**What is the current inefficiency the bot is engaging in?**
![image](https://user-images.githubusercontent.com/45623682/188891530-d43ff4df-177a-4dc6-8629-6889b8ffb4a9.png)
The amount of files in room is too high
**What should the bot be doing instead?**
I propose we add a few extra folders to better restructure them

**Comment by CarsonBurke** [comment]
Makes sense. Let me brainstorm and try out a new structure, and pitch it to the group. Thanks!
