### ISSUE TITLE
Bug: Harvesters keep dancing when 1 creep wants to go to the same location as the other

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#226]
**Describe the bug**
screeps.com/s/imFsDG
See there, both want to go to same spot
**Expected behaviour**
When 1 is at mining pos it should path around or get other sourceTarget pos

**How can we reproduce this?**
2 sources next to each other, both 1 entry 

**Potential fix**
Check if sourceContainer? is already placed at pos

**Applicable media**
![image](https://user-images.githubusercontent.com/45623682/191194149-94c20df7-919c-4e06-b7c9-b3972d918beb.png)

**Comment by pieterbrandsen** [comment]
![image](https://user-images.githubusercontent.com/45623682/191321672-3d01a0f9-377f-4e04-b863-998e199787c4.png)
@CarsonBurke  This should do it. Tested and worked. Would not work optimal but would handle the case and stop them from fighting for the same spot

**Comment by CarsonBurke** [comment]
Thanks, I have a better fix in mind relating to initial construction of sourcePositions. We also need to account for upgrade and harvest positions that can conflict like this. I’ve got it

**Comment by pieterbrandsen** [comment]
Stale, re-open if issue persists
