### ISSUE TITLE
Parameter to delete all memory or without creeps memory

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#227]
**What is the current inefficiency the bot is engaging in?**
The function deletes all memory. This means you need to kill all remaining creeps, because they do nothing anymore.
```
global.clearMemory = function () {
    // Clear all properties in memory

    for (const key in Memory) delete Memory[key as keyof typeof Memory]

    return 'Cleared all of Memory'
}
global.CM = global.clearMemory
```

**What should the bot be doing instead?**
Add a parameter to this command so it not deleting creeps memory by standard.

**Comment by CarsonBurke** [comment]
Thanks, I’ll get this done ASAP
