### ISSUE TITLE
Implement depositHarvester and depositHauler logic

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#23]

**Comment by CarsonBurke** [comment]
Panda has essentially completed this. I need to review it and make fixes and optimizations where needed

**Comment by CarsonBurke** [comment]
I'll probably implement this once some basic attack code is completed

**Comment by pieterbrandsen** [comment]
Currently not active anymore, will be again in the future
