### ISSUE TITLE
Haulers doing nothing anymore

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#239]
**Describe the bug**
Since the commit from yesterday, OPTIMIZE antifa combat logic, FEATURE combatRequest spawnGroup, the haulers don`t do anything anymore.
No speaking, too.

**Potential fix**
Changing line 34 and 80 back like before in hauler.ts.

**Comment by CarsonBurke** [comment]
I'll fix
