### ISSUE TITLE
Claimer spawn without memory

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#246]
**Describe the bug**
My room is RCL3 and a claimer got spawned. But it don't move, because the memory of it is empty.

**Expected behaviour**
It has a target room to claim in memory.

**Applicable media**
![image](https://user-images.githubusercontent.com/58844333/192618086-fc2b07b3-5180-434a-8ea9-c347ea5da513.png)

**Comment by CarsonBurke** [comment]
Void, claimers shouldn't be expected to have the target in memory
