### ISSUE TITLE
Bot don't stop to claim a room with insufficient space for the room planer

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#256]
**Describe the bug**
The bot chose a room to claim which after claimed the controller failed to design the base layout. The space of the room was not big enough. So the bot spawns vanguards all day long and they did nothing, because of the lack of construction sites.

**Expected behaviour**
If the planing for a room fails, it abandon the room for claiming for ever.

**Applicable media**
https://screeps.com/a/#!/room/shard1/E44S28

**Comment by CarsonBurke** [comment]
I'm pretty sure there is enough space in that room to plan the base. Moreover, there are already checks to stop planning when there is insufficient space that should be working. I think there is something else going on

**Comment by Aerics84** [comment]
Hmm. It had in memory all the stampAnchors for the structures, but their are empty without any pos.
