### ISSUE TITLE
Bug: From rcl5 energy input/output decreases a lot

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#265]
**Describe the bug**
When rcl5 is hit something happens where almost all speed is taken out.

**Expected behaviour**
Continue spending crazy amounts of energy

**How can we reproduce this?**
Start an private server on latest and run until rcl5

**Potential fix**
-

**Applicable media**
![image](https://user-images.githubusercontent.com/45623682/195111588-e42a2ac6-6e27-4382-895a-0b926cca4c72.png)

**Comment by CarsonBurke** [comment]
I'm sure this is due to the link placement bug. Don't worry about this until we can get that bug fixed :)

**Comment by pieterbrandsen** [comment]
Think so but then I will close it

**Comment by CarsonBurke** [comment]
Yep makes sense
