### ISSUE TITLE
No defender spawning against invaders in remote rooms

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#268]
**Describe the bug**
If a small invader spawns in a remote room and the commune is already rcl6 still no defenders fighting against it.

The first problem is, that the RemoteNeeds.minDamage or RemoteNeeds.minHeal is always 0.
Reason is in the remotesManager.ts
```
            if (remoteMemory.abandoned > 0) {
                remoteMemory.abandoned -= 1

                for (const need in remoteMemory.needs) remoteMemory.needs[need] = 0

                continue
            } 
```
Means, that after a room get abandoned it sets everything like the minDamage and the abandoned timer all the time back to 0.

If i out comment this, the remoteMemory get sets correctly.
But again, no defender get spawned.
Reason is in the spawnRequestManager.ts
```
                if (
                    rangedAttackStrength * (spawnEnergyCapacity / cost) < remoteNeeds[RemoteData.minDamage] ||
                    healStrength * (spawnEnergyCapacity / cost) < remoteNeeds[RemoteData.minHeal]
                ) {
                    // Abandon the this for some time

                    Memory.rooms[remoteName].data[RemoteData.abandon] = 1500
                    return false
                }
```
Already a small invader trigger the return false.
If i out comment the return a defender against the invader get spawned. But in my eyes the answer to it is to big.

**Expected behaviour**
If a invader in a remote room spawns, the commune spawns the smallest possible answer to it.
At the same time the room has to abandoned to stop spawning new haulers and harvesters for it. Awesome would be stopping spawn for other remote rooms, which need to travel through it, stops, too,
And creeps flee from the invader.

**How can we reproduce this?**
Spawn a invader in a remote room and print out the remoteMemory.data[RemoteData...]

**Potential fix**
Check if calculation of attackStrength and healStrength is correct, modify the needed body parts to it and control the if statement at the spawnRequestManager.ts.

**Applicable media**
![invader](https://user-images.githubusercontent.com/58844333/195182011-2491ac22-64bd-4189-a3fe-65bd5e580a18.jpg)
![defender](https://user-images.githubusercontent.com/58844333/195182013-87348582-0ef1-427a-93d0-ca76bedf18d2.jpg)

**Comment by Aerics84** [comment]
I looked again and the big body come from the partsMultiplier which want 4 * heal, because of the attack power of 40 of the invader.

**Comment by Aerics84** [comment]
I did a dirty fix to spawn different body against 1 invader attacks.
For the invader from first post this would be my answer to it:
![image](https://user-images.githubusercontent.com/58844333/195641189-ae8171b6-bdba-4da8-bec1-ea8d5a70026c.png)
850 vs 2100 energy before.

**Comment by Aerics84** [comment]
Against a boosted invader the same layout with only 850 energy cost works well, too.
Invader:
![image](https://user-images.githubusercontent.com/58844333/195655082-b248ec11-2605-4e80-af15-3e18ca1e37c6.png)
Defender after the fight:
![image](https://user-images.githubusercontent.com/58844333/195655177-f01e7cd2-a7d2-47d6-804f-720a66857dfa.png)

**Comment by CarsonBurke** [comment]
Thank you! Most of this should the fixed, the rest will be covered by antifa
