### ISSUE TITLE
If a attacker break mostly through the ramparts send all resources away

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#305]
**Describe what you want the bot to do**
Before the attacker reach the inside of a room we should transfer the resources from the storage to the terminal and transfer all of them to the neares safe room.
And we should stop to transfer back resources to the attacked room by the manageAllyRequests() and transfer only energy of needed.

Idea is to minimize losing all of the resources inside the room.

**Comment by CarsonBurke** [comment]
I love it. Will get to work on it soon
