### ISSUE TITLE
A room which i not own anymore is still inside the memory.stats

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#317]
**Describe the bug**
I lost a low rcl room and it still appears under memory.stats.rooms and shows a really high CPU usage.

**Applicable media**
![image](https://user-images.githubusercontent.com/58844333/198887870-643fe802-f7fb-4a39-8653-fc3ede96ee79.png)
![image](https://user-images.githubusercontent.com/58844333/198887902-4a0005e0-8b1e-42a4-b349-7d72a1bd2756.png)

**Comment by pieterbrandsen** [comment]
Stale
