### ISSUE TITLE
Quads breaking apart

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#357]
![image](https://user-images.githubusercontent.com/48334001/206059595-dd65c9f2-5e72-4665-8301-88e606173651.png)

- I think only 3 ended up spawning and they just walked away
![image](https://user-images.githubusercontent.com/48334001/206059719-56a3f720-8dc8-47fb-9fc1-1f1bcb118379.png)

**Comment by pieterbrandsen** [comment]
Stale, re-open if issue persists
