### ISSUE TITLE
Haulers not spawning

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#361]
![image](https://user-images.githubusercontent.com/48334001/207228010-ddb73d77-ddb8-4c15-99b6-20a783913e14.png)

**Comment by Aerics84** [comment]
I have the same problem: https://screeps.com/a/#!/history/shard1/W43S28?t=44241800
At the moment i see not the problem what brings up this bug.

**Comment by Aerics84** [comment]
**spawnRequestManager.ts**
Here is the problem, because it's **NaN**:
`partsMultiplier = this.haulerNeed`

**haulerNeedManager.ts**
If i change `room.haulerNeed += 2`
to `room.haulerNeed = 2`
it works again.
