### ISSUE TITLE
Safemode when an enemy claim creep is near the controller

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#368]
![image](https://user-images.githubusercontent.com/48334001/208348659-9b22f988-2828-4618-80da-c198bf4d3da9.png)

When an enemy creep that isn't owned by an ally with CLAIM parts is in range 3 to the controller, safemode

**Comment by pieterbrandsen** [comment]
I think its an nice feature and for sure if we use ramparts to block access. This is something for the buildingPlanner.

**Comment by CarsonBurke** [comment]
We always protect the controller with ramparts, just in this case we hadn't built ramparts yet

**Comment by pieterbrandsen** [comment]
#123 related to

**Comment by pieterbrandsen** [comment]
@CarsonBurke can we check if path is possible in our moveTo function? Including for enemy creeps
