### ISSUE TITLE
creep.findRemote() not check blocked path

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#378]
Often creep.findRemote() returns and asign a remote room to the hauler which is at the end not reachable by the path. So the hauler never recycle and blocks the commune, because it has a RN but find no path to it.

The function need to check if the remote room is reachable by path and not blocked by abandon rooms form like invaders.

**Comment by CarsonBurke** [comment]
The commune periodically checks if remotes are accessible. It should be sufficient. Checking every time a creep wants the remote seems excessive

**Comment by Aerics84** [comment]
Yea, but at the moment we never check or delete RN. So the creeps will all hang inside the commune of their remote isn't accessible anymore.

**Comment by pieterbrandsen** [comment]
Stale, re-open if issue persists
