### ISSUE TITLE
TypeError: Cannot read property 'source1RemoteHarvester' of undefined

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#42]
An error occured while upgrading to latest version

Error:
`TypeError: Cannot read property 'source1RemoteHarvester' of undefined
    at RemoteHarvester.preTickManager (main:1269:61)
    at InternationalManager.creepOrganizer (main:1342:15)
    at InternationalManager.run (main:962:10)
    at Object.loop (main:9166:26)
    at __mainLoop:1:52
    at __mainLoop:2:3
    at Object.exports.evalCode (<runtime>:15845:76)
    at Object.exports.run (<runtime>:46468:24)`
    
Harvester looks in commune.creepsFromRoomWithRemote for its remote name but it could not be found because that room isn't being remote mined currently

Code:
`RemoteHarvester.prototype.preTickManager = function () {
     if (!this.memory.remoteName) return

     const role = this.memory.role as 'source1RemoteHarvester' | 'source2RemoteHarvester'

     // Reduce remote need
     customLog('REMOTE HARVESTER CHECK', JSON.stringify(this.parts))
     Memory.rooms[this.memory.remoteName].needs[remoteNeedsIndex[role]] -= this.parts.work

     const commune = Game.rooms[this.memory.communeName]
     if (!commune) return

     // Add the creep to creepsFromRoomWithRemote relative to its remote

     console.log(commune.name, commune.creepsFromRoomWithRemote[this.memory.remoteName], this.memory.remoteName)
     commune.creepsFromRoomWithRemote[this.memory.remoteName][role].push(this.name)
}`

Logs: E72N6 undefined E72N5

*This was fixed by resetting memory using CleanMemory

**Comment by CarsonBurke** [comment]
Should be fixed :)
