### ISSUE TITLE
Commune Controller Upgraders not spawning & excessive haulers

### ISSUE THREAD

**Issue by realacesu** [CarsonBurke/The-Internationale-Screeps-Bot#427]
Branch used: main

**Describe the bug**
At an unknown times, Controller Upgraders within the main commune no longer spawn after a prolonged time such as a day or less.

I have monitored this for 1 hour after noticing this and the behavior does not change.

I have noticed excessive haulers been spawned too when this happens, I have 30 haulers at times with only one room and no available rooms on the server no remotes either. 

**Expected behavior**
At least 1 Controller Upgrader is spawned & active.

**How can we reproduce this?**

This has been noticed on the "Go Horse Brazilian" Community Server located on the server selection screen
and on shard3 of the official server.

IP: 'screeps.gohorse.dev' 

**Manual Correction for players**

Kill your creeps using `killCreeps()` to reset this. Killing off other creeps does not solve this issue.

**Comment by CarsonBurke** [comment]
Strange bug, thanks for pointing out. Can you join our [discord server](https://discord.gg/83BTa5dh) so we can discuss further?

**Comment by CarsonBurke** [comment]
Seems to only occur on Main, appears fixed on Development
