### ISSUE TITLE
remoteHauler relay resource swapping

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#488]
- Somehow they get stuck in a swapping loop
- (Wrong) Likely has to do with nextStore resource predictions, it's likely they are opposite of what they should be and are thus confusing the creep
- Not fixed by skipping ticks
- creepAtPos isn't making move request on tick after relay
- creep `this` is making a move request, swapping with creepAtPos because it isn't making one

Solutions

- Some safety check
- assigning instead of operating +/- (tried, didn't work)
- Apply present values onto nextStore changes (sorta tried, didn't work)

Diagnosis

- Perhaps the relayer is trying to go to a remote in initial path direction as the other relayer. But why then is it taking its moveRequest?

![image](https://user-images.githubusercontent.com/48334001/230756226-fcaf08ed-3e16-4eac-adf4-aae9de0c96c5.png)
![image](https://user-images.githubusercontent.com/48334001/232177344-db7666d6-42fc-443e-ad10-1e1b558e49f4.png)

![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/c08f1b7a-f045-4f3e-b9a2-0eece1012462)
-The creep is *trying* to move away
- other creep is trying to move onto creep (probably to go to other remote), probably overriding move request
-R on empty creep 
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/53ce2f7b-11cb-4916-ab85-3d517258c741)

**Comment by Araele** [comment]
I have fixed this, not sure if properly but at least I am not seeing the bug anymore, in the remoteHauler class:
I added a check
`checkForEnergyTransfer() {
    if (!this.nextStore.energy)
        return;

    const adjacentPositions = [
        { x: -1, y: -1 },
        { x: -1, y: 0 },
        { x: -1, y: 1 },
        { x: 0, y: -1 },
        { x: 0, y: 1 },
        { x: 1, y: -1 },
        { x: 1, y: 0 },
        { x: 1, y: 1 },
    ];

    for (const offset of adjacentPositions) {
        const coord = {
            x: this.pos.x + offset.x,
            y: this.pos.y + offset.y,
        };

        if (this.relayCoord(coord))
            return;
    }
}`

and then updated the relayCoord and run methods:
`run() {
    const relayResult = this.checkForEnergyTransfer();

    if (relayResult !== 'swap') {
        if (this.needsResources()) {
            this.getResources();
            return;
        }

        if (this.deliverResources()) {
            if (relayResult !== 'relay') {
                this.relay();
            }
        }
    }
}
`
`relayCoord(coord) {
    if (Memory.roomVisuals)
        this.room.visual.circle(coord.x, coord.y, { fill: customColors.lightBlue });
    const creepAtPosName = this.room.creepPositions[packCoord(coord)];
    if (!creepAtPosName)
        return false;
    const creepAtPos = Game.creeps[creepAtPosName];
    if (creepAtPos.role !== 'remoteHauler')
        return false;
    if (creepAtPos.movedResource)
        return false;
    if (!creepAtPos.freeNextStore)
        return false;
    if (creepAtPos.freeNextStore !== this.usedNextStore)
        return false;
    this.transfer(creepAtPos, RESOURCE_ENERGY);
    this.movedResource = true;
    creepAtPos.movedResource = true;
    const nextEnergy = Math.min(this.store.energy, creepAtPos.freeNextStore);
    this.nextStore.energy -= nextEnergy;
    creepAtPos.nextStore.energy += nextEnergy;
    delete this.moveRequest;
    delete creepAtPos.moveRequest;
    delete this.moved;
    delete creepAtPos.moved;
    delete this.memory.P;
    delete creepAtPos.memory.P;

    // Check if the creeps should swap places or just relay energy
    if (creepAtPos.store.energy === 0 && this.store.energy === this.store.getCapacity()) {
        // Swap places
        const tempMemory = creepAtPos.memory;
        creepAtPos.memory = this.memory;
        this.memory = tempMemory;
        return 'swap';
    } else {
        // Relay energy
        creepAtPos.memory.RLRs = this.memory.RLRs;
        this.memory.RLRs = [];
        this.getResources();
        const remoteHauler = creepAtPos;
        remoteHauler.deliverResources();
        return 'relay';
    }
}
`
with this the creeps will either relay or swap places depending on their store conditions, if the target creep has no energy and the current creep is full they will swap otherways they will relay
