### ISSUE TITLE
Double sourceHarvester spawning

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#502]
![image](https://user-images.githubusercontent.com/48334001/229415701-0146d42c-dd7f-45d3-94ce-1bb5ee5ba3e7.png)

- RCL 4
- 6 WORK
- 850 cost (biggest)

**Comment by realacesu** [comment]
#427 could be related

**Comment by CarsonBurke** [comment]
> #427 could be related

Definitely not, but thanks
