### ISSUE TITLE
Building loop between controller container and link

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#543]
If we are rcl5 and can place a link near the controller the bot is destroying the container / link in a loop and rebuild it.
I think the problem is that the bot is not sure which building have to be their and always thinks it the "wrong" one at this position.

The behavior coming from the function `private placeBase(RCL: number, maxCSites: number)` and here the line `structure.destroy()`.

**Comment by CarsonBurke** [comment]
Please check with latest commit (not on MMO) to see if this is fixed
