### ISSUE TITLE
The bot spawns 2 harvesters for source 0

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#545]
I have two rooms on my private server and till rcl7 in both rooms the bot always spawns 2 harvester for the source 0.
The source 1 has always only 1 harvester.

**Comment by CarsonBurke** [comment]
Please check with latest commit (not on MMO) to see if this is fixed

**Comment by Aerics84** [comment]
No, it still spawns in late rcls more then 1 harvester.
