### ISSUE TITLE
Spawning bugs

### ISSUE THREAD

**Issue by Aerics84** [CarsonBurke/The-Internationale-Screeps-Bot#576]
- [x] Sometimes in different rooms not all 4 fastFillers get spawned. It could happen that a few thousand ticks one fastFiller is missing, but it recovers by itself and spawning it again.
- [x] After some days in different rooms the haulerNeed "explode" and overspawn them. After a memory reset it is fine again, but the problem happens again.
- [ ] Sometimes it spawns 2 remoteHarvesters with maximum size. At other sources the bot works correct and spawn only 1 harvester.

**Comment by CarsonBurke** [comment]
Please make each one a task:
```
- [ ] task name
```

Or make a separate issue for each
