### ISSUE TITLE
Fix basePlanner not accounting for impassible tiles in placement

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#60]
![image](https://user-images.githubusercontent.com/48334001/177222597-02ffa415-ebf5-43d5-b88a-ef30acbed632.png)

**Comment by pieterbrandsen** [comment]
![image](https://user-images.githubusercontent.com/45623682/177416800-f4893e9f-dd54-44da-ae0e-0b6968bce613.png)
Bottom right, thinks it can go through but didn't build an road

**Comment by CarsonBurke** [comment]
I'm entirely unsure how this is being planned. Anyone else have an idea?
