### ISSUE TITLE
harvest positions fail

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#624]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/b87c58a3-cc23-453e-b934-0a3136f7dec5)

- on MMO
- https://screeps.com/a/#!/room/shard2/W27S1
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/f03e1f37-08b7-468e-900a-5bbda076222d)

**Comment by DefaultO** [comment]
Duplicate of https://github.com/The-International-Screeps-Bot/The-International-Open-Source/issues/697 and fixed. You can close this one. @CarsonBurke

**Comment by CarsonBurke** [comment]
> Duplicate of #697 and fixed. You can close this one. @CarsonBurke

Thanks, done
