### ISSUE TITLE
Improvement: lower rcl towers closer to the base

### ISSUE THREAD

**Issue by DefaultO** [CarsonBurke/The-Internationale-Screeps-Bot#625]
**What is the current inefficiency the bot is engaging in?**
It can happen that the current base planner places the first towers very far away from the base itself. This can result in the bot dealing the least amount of damage possible. An Example would be this room: https://screeps.com/season/#!/room/shardSeason/W4N29
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/42414542/eb5522ee-e6ca-48b5-8c1e-3caf5611a3c2)

As you can see the Tower for RCL3 gets planned to get placed in the top right. I see the benefit of having towers right next to the ramparts. It boosts the damage your defense deals by a lot. Resulting in a more dangerous defense. But I believe the first tower of this commune on the other side of the room isn't helping a lot in defending it. Especially since there are no ramparts.
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/42414542/880bead9-a9c7-4ff8-8087-5eb4d90fcecd)

**What should the bot be doing instead?**
Keep early towers as close as possible to the base itself. So that damage is the highest possible the closer an enemy gets to the base. This can be achieved by ordering the tower positions by distance to some middle point of the base. And assigning them in such a way that lower RCL towers are assigned to the closer tower positions.

But it would also be fine if that only applies to your first tower. I leave the implementation to you.

**Comment by CarsonBurke** [comment]
Thank you, this is a great issue in content :)
I think I have a solution in mind, forcing the first tower to be the one closest to an origin point - probably the hub or fastFiller anchor

**Comment by DefaultO** [comment]
Commits e2f336b6bc3603dbf488f9ac9888a5a1521accbb & ee34566d9da306e55de32ab47b582228865b816c implemented this improvement.
