### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by JacobPlaysGames** [CarsonBurke/The-Internationale-Screeps-Bot#626]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/80339878/9ebf0dc4-76bd-4683-af59-665bd0329af5)

**Comment by CarsonBurke** [comment]
@JacobPlaysGames What version and branch of the bot are you running? can you identify the commit for me?

**Comment by JacobPlaysGames** [comment]
Seems to be anything after commit f6b1679

**Comment by CarsonBurke** [comment]
Hah, I ended up fixing this but didn't close the issue. Can you update to latest and confirm the fix? :)

**Comment by JacobPlaysGames** [comment]
Same issue as of commit c8df9bb
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/80339878/f93128dc-e308-40ad-adf4-0e3a7b1159b6)

**Comment by CarsonBurke** [comment]
You reopened it, is it not resolved on more recent commits?

**Comment by JacobPlaysGames** [comment]
It is not resolved on the most recent commit. My bad. Accidentally closed it.

**Comment by CarsonBurke** [comment]
I'll debug and try to come up with a proper fix then
