### ISSUE TITLE
creep moving back and forth as the spawn tries to shove them

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#645]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/8910ad8a-b9b7-44b7-a352-85c95448155e)

- spawn shoves them
- spawn probably reserves the position after the creep in the way when it tries to reserve it for the spawning creep. Thus the blocking creep moves back, stopping spawning totally

**Comment by Mdashad071192** [comment]
> ![image](https://user-images.githubusercontent.com/48334001/249621615-8910ad8a-b9b7-44b7-a352-85c95448155e.png)
> 
> * spawn shoves them
> * spawn probably reserves the position after the creep in the way when it tries to reserve it for the spawning creep. Thus the blocking creep moves back, stopping spawning totally
