### ISSUE TITLE
claimed room not being registered as a commune

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#646]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/e5dcc602-c19d-43c0-9e23-580ea0d9eac7)

![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/f38b9893-1f3b-467b-987d-6edf69a276c4)

It's still being used as a remote

**Comment by DefaultO** [comment]
Done? If not, I assume we could do the extra logic whenever we claim a room. So it doesn't run every single tick or more often than is necessary.

How to reproduce? Expansion into one of the active remotes?

**Comment by realacesu** [comment]
Should be resolved?
@CarsonBurke
