### ISSUE TITLE
Failed to find stampAnchor

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#657]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/d996ebda-3a29-47b5-8af4-d58bf198f3b0)

error handling, stop plan attempt when this happens
failed to generate a startCoord for labs

**Comment by pieterbrandsen** [comment]
Reopen when it appears in the error logs in discord.
