### ISSUE TITLE
quads misjudging the heal they have and thus damage they can take

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#658]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/7e112596-6d5d-434d-8f8a-61b76ceb5b30)

**Comment by pieterbrandsen** [comment]
How do you know this is the case? Dont understand the complete code but looks good to me

**Comment by CarsonBurke** [comment]
The code is pretty but must be broken somewhere, because they can outheal the damage from this invader

**Comment by pieterbrandsen** [comment]
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/3f494c9408cbf016068c8feb551c44aca5cd7b62/src/room/creeps/creepAdditions.ts#L206

Heal judging looks good, but maybe the judged ranged attack is wrong?


~~What if they not misjudged the heal but just take the whole room into considiration?~~
Will need to look into it with an quad.
