### ISSUE TITLE
Lower threshold for repairing general structures when under attack

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#661]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/491e7df8-4756-44b2-a256-80f426b76168)

**Comment by pieterbrandsen** [comment]
@CarsonBurke What if we only repair structures inside the ramparts? Can we get some range on this?

**Comment by CarsonBurke** [comment]
I think that's fair in most cases

**Comment by CarsonBurke** [comment]
it's expensive to do, but It should be done. Can you make an issue on it please?
