### ISSUE TITLE
towers not attacking with positive damage values

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#664]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/4e7b2c09-ee14-46a9-82e5-75a85822171f)

**Comment by pieterbrandsen** [comment]
@CarsonBurke positive as in creep heals 10, we shoot 20 which is an positive 10 damage. And dont shoot when negative?

This would be an feature request but we could assign expectedDamage to an enemy creep, when creep + tower = 30, when creep heals 20 it should attack to make it an positive number

**Comment by CarsonBurke** [comment]
We have things alike to expectedDamage.  This is a bug report because the system is wrong in some cases, like this one

**Comment by pieterbrandsen** [comment]
#658 
Maybe related to each other.

**Comment by CarsonBurke** [comment]
I agree it might be the same problem.

However my leading guess on this one is that its judgement of "close range from exit" and thus carefulness in shooting (as to not waste energy on fleeing and returning creeps) is incorrect in some way.
