### ISSUE TITLE
Ineffective progression in early RCL

### ISSUE THREAD

**Issue by realacesu** [CarsonBurke/The-Internationale-Screeps-Bot#678]
Using Latest Commit as of Aug. 13th 2023 @ 20:00PM EST 

**Describe the bug**
Ineffective RCL progression in Early RCL (1-2 possibly higher but untested)

Ineffective spawning for controllerUpgraders(excessive) and maybe remoteHaulers(excessive)  -- *possibly also logistics requests for controllerUpgraders as they sit idle for a long time*

**Expected behaviour**
Typical International Bot RCL progression 

**How can we reproduce this?**
I recently respawned on S+ and MMO this bug has had me at RCL 2 for a prolonged time on MMO and S+

**Potential fix**
Was spawning modified recently? There was reorganization done for collectivized commits. May take a while to find this bug

**Applicable media**
Screenshots are from the S+ server.

https://i.imgur.com/aEXDdcy.png
https://i.imgur.com/4StwjYb.png
edit still RCL 2 and spawning a 4th controller upgrader -- https://i.imgur.com/5DaGnUc.png

**Comment by CarsonBurke** [comment]
- threatened values were applied when there was no threat, breaking the memory value
