### ISSUE TITLE
remotehaulers stuck

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#690]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/52ed59c0-8dbb-4fce-b613-a8fa4e71a172)
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/bbe0d8ab-2442-4f80-8cbd-21b5986d004a)

- creep goes off-path to get resource
- other creep tries to go to same resource
- neither creep moves

**Comment by pieterbrandsen** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/364b1d56-1396-409b-9d80-c7a582a522dd)
This for no path creeps, being called 2 times to create move request for some reason

**Comment by pieterbrandsen** [comment]
2 Creeps want to go to the same pos, further then that I am lost.

No fixing itself happening. When one is lost, the next creates the bug again

**Comment by CarsonBurke** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/384172d9-ef61-4f39-89d1-7294bd09d3e4)

**Comment by pieterbrandsen** [comment]
@CarsonBurke  Hadnt you pushed an fix for this?

**Comment by CarsonBurke** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/b2f7fc26-901f-4ea5-b547-53a1ebb110a5)

- interesting situation where they fail to reconcile
- killing the energy-holding creep didn't fix the problem

**Comment by CarsonBurke** [comment]
> @CarsonBurke Hadnt you pushed an fix for this?

no

**Comment by CarsonBurke** [comment]
> ![image](https://user-images.githubusercontent.com/48334001/270512444-b2f7fc26-901f-4ea5-b547-53a1ebb110a5.png)
> 
> * interesting situation where they fail to reconcile
> * killing the energy-holding creep didn't fix the problem

taking this to a separate issue, seems to be a different bug
