### ISSUE TITLE
No closest harvest pos

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#697]
**Commit or otherwise version of the bot**

**Describe the bug**

**Expected behaviour**
No error

**How can we reproduce this?**
I suspect when remoting in reserved room of enemy player

**Potential fix**
First 0 is terrainCoords, which is wrong. Maybe harvest positons are not set correctly

**Applicable media**
![269074444-90001913-b7e6-4ce9-9c72-82bf9d04e64e](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/48e0b6d8-bfe2-4408-bd4a-19b4e043d8c1)
![269074462-2b147977-3078-41dd-90c8-6e4531fda5ce](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/686f94e7-9897-454f-ab3c-a37ea9c5f41e)

**Comment by pieterbrandsen** [comment]
@DefaultO 

The 4 SHOULD be valid, atleast basecoords shoudlnt be 255

https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L1281

I linked where the controller sets its baseCoords, maybe both sync up? Must be the case almost


To your comment, those are the "valid positions" but baseCoord is invalid, its an ragged array(one inside another) so no [i] inside there

**Comment by pieterbrandsen** [comment]
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L882
Maybe there are not ignored?

**Comment by DefaultO** [comment]
@pieterbrandsen I assumed the "0 0" in the console output, at least one of them, was the value inside that ``baseCoords`` array at that tile position. That's why I thought those are valid indeed. Did I assume wrong? If that's the case, that avoid function you found can't be the cause for it to not find any valid position (because those baseCoords tiles around the source aren't all set to 255).

There aren't a lot of things happening at the code that throws that "no closest harvest pos ..." error. If you get past that "get adjacent tiles of a source and push the positions to that valid positions array" part, and that valid positions array contains those four positions. It must be the sort. I could be wrong.

I am just remembering the time I tried to debug this. And I thought it was the baseCoords check that removed those. I would debug this in practice. But I can't get the current version built really.

**Comment by DefaultO** [comment]
The cause of it not having any valid harvest positions for some sources must be somewhere between:
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L963
and:
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L1005

**Comment by pieterbrandsen** [comment]
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L973

Base coord MUST BE 255, which is currently the second 0 so 0

**Comment by pieterbrandsen** [comment]
Default, lets contine on discord, please add me :)

**Comment by DefaultO** [comment]
> https://github.com/The-International-Screeps-Bot/The-International-Open-Source/blob/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab/src/room/communePlanner.ts#L973
> 
> Base coord MUST BE 255, which is currently the second 0 so 0

~~So the 4 other positions should be there since they got 255.~~
But no. Since they got terrain 255. Crap. So you were right. Terrain isn't correct. Or the baseCoords array.

> Default, lets contine on discord, please add me :)

Will do.
Edit: I don't have your Discord handle.

**Comment by pieterbrandsen** [comment]
The 4 I crossed on the screenshot are the 0 0 positions, but sources arent avoided so 255 is what they get.

**Comment by CarsonBurke** [comment]
```ts
        for (const coord of findCoordsInRange(this.room.controller.pos, 2)) {
            const packedCoord = packAsNum(coord)
            this.baseCoords[packedCoord] = this.terrainCoords[packedCoord]
        }
```
this is the line that causes the issue

**Comment by pieterbrandsen** [comment]
I noticed that, we can change it to 1 instead of 2 and this would fix it

**Comment by CarsonBurke** [comment]
I will test a fix in a moment. I think it will resolve this issue. Thanks!

**Comment by CarsonBurke** [comment]
Recent test seems to resolve this issue, though it apparently has caused a new one: #698

**Comment by DefaultO** [comment]
> Recent test seems to resolve this issue, though it apparently has caused a new one: #698

Has the fix been commited already? Then referencing it like I did [here](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/issues/625#issuecomment-1729116411) from now on makes it way easier to keep track. Spent 20 minutes to find all commits that affected the tower code to determine if my suggestion can be closed or not.

**Comment by pieterbrandsen** [comment]
The fix has been pushed
@DefaultO 
https://github.com/The-International-Screeps-Bot/The-International-Open-Source/commit/57198cc4c95bab4e6ff944fd8a8ff6f89de07dab
