### ISSUE TITLE
Creep shoving allowed based on role

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#700]
**What is the current inefficiency the bot is engaging in?**

**What should the bot be doing instead?**
Lets stop shoving harvesters, and maybe other rolea also

**Comment by CarsonBurke** [comment]
I think this is a half-thought through solution to harvesters being pushed. Instead, creeps should inform that they don't want to be shoved, and other creeps should respect this.

**Comment by CarsonBurke** [comment]
Addressed in #702
