### ISSUE TITLE
Better build priority

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#703]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/b2057c07-9461-4f9b-9256-24bd2d810780)

Problem: for the fastFiller, the first container should be build before the extensions, however the second container should only be built for the extensions it serves, and not when those extensions are not ready to be built. This issue extends to other parts of build order logic

- We could place for / build for 1 RCL at a time, however we want things like towers, storage to be prioritized, and factory, labs, extractor not so much
- We could hypothetically add a build priority property to planning data, but this seems impractical in terms of internal complexity and reasonable assignment
- Other options?

**Comment by CarsonBurke** [comment]
Currently I'm just looking for ideas on how to solve this problem. Thanks

**Comment by pieterbrandsen** [comment]
Okay

Op vr 22 sep 2023 om 08:14 schreef Carson ***@***.***>

**Comment by pieterbrandsen** [comment]
@CarsonBurke 

We could create while planning the order we construct it.

Some construction sites like the fast filler container should block until its build.
