### ISSUE TITLE
Wildly inaccurate energy outcome stats

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#704]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/812cfc86-a3c5-4fba-9e7b-2908a2993e7d)

energy out stats are extremely high for an unknown reason. Started after I updated a few commits forward a few hours ago. https://grafana.pandascreeps.com/d/bb896168-2708-4582-b2d9-7ac866e54a98/user-data?orgId=2&refresh=5s&var-Server=screeps_com&var-Shard=All&var-Username=MarvinTMB&var-Username=PandaMaster&var-Rooms=All&from=now-6h&to=now

Essentially latest commit
Sadly I do not have much more information to provide

**Comment by pieterbrandsen** [comment]
Issue is in the global, when I just uploaded code it all fixed itself

**Comment by CarsonBurke** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/b1aec220-be9b-47d0-b5c2-7064f2ff0139)
Stats are dropping, seem to be corrected with a couple fixes to spawning
