### ISSUE TITLE
spawnRequestVisuals Flag prohibits spawning

### ISSUE THREAD

**Issue by realacesu** [CarsonBurke/The-Internationale-Screeps-Bot#708]
**Commit or otherwise version of the bot**
commit SHA ad5b7bf278229998be87ab710b0d2f6ca2680039
**Describe the bug**
with the spawnRequestsVisuals Flag active. Spawns do not spawn creeps
**Expected behaviour**
spawning occurs while this debug flag is active
**How can we reproduce this?**
Create the spawnRequestsVisuals Flag
**Potential fix**
N/A
**Applicable media**

**Comment by pieterbrandsen** [comment]
How would I create the flag?

**Comment by CarsonBurke** [comment]
Interesting thanks. I'll review the code but I think this is a correlary and not a causal effect

**Comment by CarsonBurke** [comment]
Okay this is a causal relationship. Very strange. And it only happens sometimes. Could someone help look at the code `spawningStructures.ts` LOC 699-726 please to see what's up? I don't understand why it is breaking spawning

**Comment by pieterbrandsen** [comment]
From an short investigation, we reset spawnRequests, but most importantly we use the orginal array which maybe already had reservations.

**Comment by CarsonBurke** [comment]
Yeah, I need more :/
