### ISSUE TITLE
Builders not building

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#709]
**Commit or otherwise version of the bot**
No building happening

**Describe the bug**

**Expected behaviour**

**How can we reproduce this?**
Spawn in fresh room, http://pandascreeps.com:21025

**Potential fix**
Reservation system fix?

**Applicable media**
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/1a26796d-f8b5-4ef4-825a-de7dbdc4df99)

**Comment by CarsonBurke** [comment]
- what does fastFiller containers equal?
- can you show with roomLogisticsVisuals enabled?

**Comment by pieterbrandsen** [comment]
How do I do the second?

**Comment by pieterbrandsen** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/927d7da7-9d77-4f0a-abd9-22f9670b82d6)
In th mean time, it has build but upgraderes arent picking up energy as there is no container yet

**Comment by CarsonBurke** [comment]
> How do I do the second?

global.settings.roomLogisticsVisuals, or something like that

**Comment by CarsonBurke** [comment]
> ![image](https://user-images.githubusercontent.com/45623682/270182094-927d7da7-9d77-4f0a-abd9-22f9670b82d6.png) In th mean time, it has build but upgraderes arent picking up energy as there is no container yet

There shouldn't be any upgraders if the container isn't built. Please confirm if there are / aren't? Looks like those are builders?

**Comment by pieterbrandsen** [comment]
Cant check anymore the role, but I guess your correct that it are builders.

**Comment by pieterbrandsen** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/9a4f3ae1-1af3-4a54-acbf-e46f51eb021e)
There is more then enough energy based on the reservations.

But the builders still not picking up

**Comment by CarsonBurke** [comment]
Thanks

**Comment by pieterbrandsen** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/45623682/05311364-f258-4865-a952-2354e37e23b0)
Builders get energy themself from the left source, where the rest waits on energy
