### ISSUE TITLE
Potential controllerLink / upgrade position planning failure

### ISSUE THREAD

**Issue by crazykid080** [CarsonBurke/The-Internationale-Screeps-Bot#722]
**Commit or otherwise version of the bot**
2.112.0 (4e3e7e344f8a30434ea769f3cca72612a9964375)
**Describe the bug**
Creep attempting to path onto controller link 
RCL 6, default WCM creep (name: 3_200_W8S2_3_8).
**Expected behaviour**
My assumption is that the creep should be pathing onto a tile around the link, but I cannot be sure
**How can we reproduce this?**
Unknown
**Potential fix**

**Applicable media**
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/10173541/33f1c892-f3c4-4aa2-8086-703340974076)
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/10173541/48b46eb2-89f4-461a-9eb1-5ace78694d81)

**Comment by CarsonBurke** [comment]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/9bc51f13-992a-42b2-9ce0-23f4f4f2b0c7)
- it's plausible though unknown that this upgrader might be experiencing the same bug

**Comment by CarsonBurke** [comment]
Seems like caching `_upgradePositions` inter tick was allowing the controllerLink to be ignored pre global reset
