### ISSUE TITLE
Track registered intents each tick

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#735]
- Record in Memory.stats
- Will allow for better CPU diagnosis -- are we using our CPU mostly on intents, or wasting it elsewhere?
- Will take some time to implement everywhere

### Progres

- [ ] creep movement
- [ ] harvesting
- [ ] towers
- [ ] upgrading
- [ ] building
- [ ] repairing
- [ ] logistics
- [ ] terminal
- [ ] link
- [ ] spawn
- [ ] renew
- [ ] recycle
- [ ] relaying
- [ ] reserving
- [ ] core attacking
- [ ] remote builder
- [ ] mineral harvester

**Comment by realacesu** [comment]
What are your thoughts are wrapping the intent prototypes to implement this? Or should we be implementing this in the function that calls the intent so we can track how the intent is being used (i.e. for 'remote building')

**Comment by CarsonBurke** [comment]
No messing with prototypes :)
