### ISSUE TITLE
Relaying problem still exists!!! :( sadge

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#736]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/d693dcf9-b74f-4cff-af2c-464757c7e742)

**Comment by realacesu** [comment]
After recent hauler updates, is this resolved? Only thing I can think of is excessive remote haulers making a breadline after recent updates.

@CarsonBurke
