### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by OfficialAudite** [CarsonBurke/The-Internationale-Screeps-Bot#743]
**What is the current inefficiency the bot is engaging in?**
Not the bot but the project.

Add .nvmrc with node version inside.
`node -v > .nvmrc`

It helps to know which version is needed to run the project.

**Comment by realacesu** [comment]
This is already present on the development branch.

**Comment by OfficialAudite** [comment]
> This is already present on the development branch.

So Master branch is just behind for current beeing ?

**Comment by DefaultO** [comment]
> > This is already present on the development branch.
> 
> So Master branch is just behind for current beeing ?

Yes. Dev hasn't been stable enough to merge with main. We don't like that either. But it is what it is. New features and improvements get added instead of focusing on old issues.
