### ISSUE TITLE
Improvement: README not complete/outdated

### ISSUE THREAD

**Issue by DefaultO** [CarsonBurke/The-Internationale-Screeps-Bot#762]
Hello @CarsonBurke, nice to see you working on the Bot again. Is it intentional that the README is not noob friendly and misses out some extra steps that have to be taken to compile the bot successfully? If it is intentional, let me know, and get rid of the issue. Something I encountered while trying to get the new version working.

One example of missing steps:
- _src/other/userScript/userScript.example.ts_ has to be copied and pasted and the copy renamed to _userScript.ts_
- the same file has to be edited:
`class UserScriptExample` -> `class UserScript`
`global.userScript = new UserScriptExample()` -> `global.userScript = new UserScript()`

One Outdated example:
- "Make sure your node version is below 17.0.0". This is outdated or false information, since you are using packages that require a node version (engine) greater or equal to 18, such as rollup. I managed to compile it using the current LTS Node.js version (20.10.0).

**Comment by awropcd** [comment]
hi im not a developer, just an user but just to mension "npm i" at the start of the readme.md is same as npm install

**Comment by DefaultO** [comment]
> hi im not a developer, just an user but just to mension "npm i" at the start of the readme.md is same as npm install

I could swear it wasn't there the last time I checked the readme. But I must have overread it. I wouldn't have written it like that if I had caught it. Removed that point then.
