### ISSUE TITLE
Movement swapping oscillation

### ISSUE THREAD

**Issue by CarsonBurke** [CarsonBurke/The-Internationale-Screeps-Bot#768]
![image](https://github.com/The-International-Screeps-Bot/The-International-Open-Source/assets/48334001/657508cb-e0da-4c8c-b7e2-af6026c1456e)

the two repairers on the top left are going back and forth forever.
almost 100% to due with the fastFiller creeps fighting over the same fastFiller stationary hauling position.

**Comment by realacesu** [comment]
Noticed this with haulers and other creeps (scouts and maintainers). this doesn't happen only due to fastfiller but maybe in this occurrence. For me this occurs near my hub

**Comment by realacesu** [comment]
Will check traffic priorities if I can find it. But if you made a commit that modifies this behavior recently can you link it?

**Comment by CarsonBurke** [comment]
I've got unpushed commits that appear to fix the fastFillerPosition issue that seemed to be the underlying cause of the oscillation

**Comment by CarsonBurke** [comment]
> Noticed this with haulers and other creeps (scouts and maintainers). this doesn't happen only due to fastfiller but maybe in this occurrence. For me this occurs near my hub

If see this happening without fastFiller creeps involved, please link history :)
