### ISSUE TITLE
Bug: Bot unclaiming room(s) on initial set-up

### ISSUE THREAD

**Issue by DefaultO** [CarsonBurke/The-Internationale-Screeps-Bot#772]
Since you asked me to open an issue for this. The version was the one around the time I posted the readme "issue". So I believe before your "fix hauler reaction time" commit.

The issue: The bot is unclaiming RCL8 room(s) on initial set-up.

This was one of the rooms, but since this event happened a long time ago, we can't look at the exact time it happened for clues.
https://screeps.com/a/#!/history/shard1/W58N57?t=50800000

What could hint you to a problem: I think my memory was messed up because I was running the "Piki" bot from one of the YP members. And commie didn't bother clearing the memory beforehand. So maybe you have code that is checking if there is a colony entry in the memory, and if not, unclaim.

Will keep you updated. Planning to look through the code for "unclaim" calls. If it's inside the WASM module, you probably have to look through that yourself (since I don't know if the code is available to us).

**Comment by DefaultO** [comment]
Yea so I believe the "roomPruning" is the reason why that is happening. Based on my understanding, it loops through all owned rooms, and checks if they are RCL8. Gets the best commune (?), and if you have more than one RCL8 room, it sets abandonCommune to true for the best commune (?).

But that would be weird that it happens on the initial set-up. Because that `sleepFor` should make it wait for at least 50000 ticks, if that's what `isSleepingResponsive()` does. I replaced the function calls with the code inside the functions, so that you can understand the logic without having to look up everything.
```ts
isSleepingResponsive() {
        if (this.sleepUntil > Game.time) return true // <-- this.sleepUntil should be undefined at initial launch

        this.sleepUntil = Game.time + this.sleepFor // this is the first time this.sleepUntil is getting defined, a bit too late
        return false // we will return the first time because the if-statement fails
    }
```

> [!IMPORTANT]
> Edit: I think because of the `this.sleepUntil = Game.time + this.sleepFor` line / `sleepWhenDone()` function call not being above the if-statement. We will run through that `RoomPruningManager.run()` on the first tick of the bot or the first tick after room planning (because we will run out of CPU initially).
>
> I agree that we want to improve our overall rooms (just like Tigga), but this room pruning system doesn't feel safe at all.


I wasn't able to find anything else that could do it when looking for "unclaim" or "abandonCommune". No DefaultO-traps, nothing. Those are at most inside the wasm module that only you can look through to find an `unclaim()` or `abandonCommune` reference.

```ts
export class RoomPruningManager extends Sleepable {
    sleepFor = randomIntRange(50000, 100000)
    run() {
        if (this.isSleepingResponsive()) return

        // Make sure all rooms are max RCL
        // Temple rooms?

        let rooms = 0
        let highestCommuneScore = 0
        let highestCommuneScoreCommuneName: string

        for (const roomName of collectiveManager.communes) {
            const room = Game.rooms[roomName]
            if (room.controller.level < maxControllerLevel) return

            rooms += 1

            const roomMemory = Memory.rooms[roomName]
            const score = roomMemory[RoomMemoryKeys.score] + roomMemory[RoomMemoryKeys.dynamicScore]

            if (score <= highestCommuneScore) continue

            highestCommuneScore = score
            highestCommuneScoreCommuneName = roomName
        }

        // Have multiple rooms before we unclaim
        if (rooms <= 1) return

        // Find the lowest scoring workRequest
        const lowestWorkRequestScore = findLowestScore(
            Object.keys(Memory.workRequests),
            roomName =>
                Memory.rooms[roomName][RoomMemoryKeys.score] +
                Memory.rooms[roomName][RoomMemoryKeys.dynamicScore],
        )
        // The best work request must be better than our worst commune
        if (lowestWorkRequestScore >= highestCommuneScore) return

        Memory.rooms[highestCommuneScoreCommuneName][RoomMemoryKeys.abandonCommune] = true
    }
}
```

**Comment by CarsonBurke** [comment]
Thanks. I noticed my notes were different from the code. It should only have been running when all rooms were RCL 8, but was actually running if there was any RCL 8. This has been resolved and will be pushed soon.
