### ISSUE TITLE
Wrong comment or maths

### ISSUE THREAD

**Issue by lokenwow** [CarsonBurke/The-Internationale-Screeps-Bot#8]
/src/room/linkFunctions.ts

Either comment or maths is wrong.
Comment suggests half but maths of *0.25 is quarter. 

lines 25 || 27

`        
            // If the link is more than half full, iterate

            if (receiverLink.store.energy > receiverLink.store.getCapacity(RESOURCE_ENERGY) * 0.25) continue
`

**Comment by CarsonBurke** [comment]
Wrong comment, thanks. Will fix
