### ISSUE TITLE
Scout gets stuck in enemy territory, and keeps retrying

### ISSUE THREAD

**Issue by DefaultO** [CarsonBurke/The-Internationale-Screeps-Bot#81]
Huge CPU usage due to Scout getting stuck in enemy territory. Pathfinding failing. Changes scouting target constantly.
Room affected by this: https://screeps.com/a/#!/room/shard2/E58S37

``
Incomplete Path:
[room E58S37 pos 48,27],[room E58S37 pos 47,28],[room E58S37 pos 47,29],[room E58S37 pos 47,30],[room E58S37 pos 47,31],[room E58S37 pos 47,32],[room E58S37 pos 47,33],[room E58S37 pos 47,34],[room E58S37 pos 47,35],[room E58S37 pos 47,36],[room E58S37 pos 47,37],[room E58S37 pos 47,38],[room E58S37 pos 46,39],[room E58S37 pos 45,40],[room E58S37 pos 44,41],[room E58S37 pos 43,42],[room E58S37 pos 42,42],[room E58S37 pos 41,43],[room E58S37 pos 40,43],[room E58S37 pos 39,43],[room E58S37 pos 38,42],[room E58S37 pos 37,41],[room E58S37 pos 36,40],[room E58S37 pos 35,40],[room E58S37 pos 34,40],[room E58S37 pos 33,40],[room E58S37 pos 32,40],[room E58S37 pos 31,40],[room E58S37 pos 30,40],[room E58S37 pos 29,40],[room E58S37 pos 28,40],[room E58S37 pos 27,40],[room E58S37 pos 26,40],[room E58S37 pos 25,40],[room E58S37 pos 24,39],[room E58S37 pos 23,38],[room E58S37 pos 22,38],[room E58S37 pos 21,38],[room E58S37 pos 20,38],[room E58S37 pos 19,38],[room E58S37 pos 18,38],[room E58S37 pos 17,38],[room E58S37 pos 16,38],[room E58S37 pos 15,38],[room E58S37 pos 14,38],[room E58S37 pos 13,38],[room E58S37 pos 12,38],[room E58S37 pos 11,38],[room E58S37 pos 10,38],[room E58S37 pos 9,38],[room E58S37 pos 8,38],[room E58S37 pos 7,38],[room E58S37 pos 6,38],[room E58S37 pos 5,38],[room E58S37 pos 4,38],[room E58S37 pos 3,38],[room E58S37 pos 2,38],[room E58S37 pos 1,38],[room E58S37 pos 0,38],[room E57S37 pos 49,38],[room E57S37 pos 48,37],[room E57S37 pos 47,36],[room E57S37 pos 46,35],[room E57S37 pos 45,34],[room E57S37 pos 44,33],[room E57S37 pos 43,32],[room E57S37 pos 42,31],[room E57S37 pos 41,30],[room E57S37 pos 40,29],[room E57S37 pos 40,28],[room E57S37 pos 40,27],[room E57S37 pos 40,26],[room E57S37 pos 40,25],[room E57S37 pos 40,24],[room E57S37 pos 40,23],[room E57S37 pos 40,22],[room E57S37 pos 40,21],[room E57S37 pos 40,20],[room E57S37 pos 40,19],[room E57S37 pos 40,18],[room E57S37 pos 40,17],[room E57S37 pos 41,16],[room E57S37 pos 42,15],[room E57S37 pos 43,14],[room E57S37 pos 44,13],[room E57S37 pos 45,12],[room E57S37 pos 46,11],[room E57S37 pos 47,10],[room E57S37 pos 48,9],[room E57S37 pos 48,8],[room E57S37 pos 48,7],[room E57S37 pos 48,6],[room E57S37 pos 48,5],[room E57S37 pos 48,4],[room E57S37 pos 49,3],[room E58S37 pos 0,3],[room E58S37 pos 1,2],[room E58S37 pos 2,1], {"x":25,"y":25,"roomName":"E58S36"}
``

What it instead should do is ignore such a room for the future, or check it out once, fail, and then move somewhere else. Instead of hopping between the room that is affected and the room next to it.

**Comment by CarsonBurke** [comment]
This is fixed on development branch now
