### ISSUE TITLE
Scouts stuck in loop

### ISSUE THREAD

**Issue by lokenwow** [CarsonBurke/The-Internationale-Screeps-Bot#9]
If a scout finds a room it wants to sign but a reserver is there that "unsigns" it immedietly the scout will get caught in a loop of signing every 2 ticks.

https://github.com/CarsonBurke/The-International-Screeps-Bot/blob/Typescript-(Main)/src/room/creeps/roleManagers/international/scoutManager.ts#L40

**Comment by CarsonBurke** [comment]
Thanks for the issue! I'll get to work on fixing this
