### ISSUE TITLE
Base building planning is un-optimally planning extension stamps

### ISSUE THREAD

**Issue by pieterbrandsen** [CarsonBurke/The-Internationale-Screeps-Bot#94]
![image](https://user-images.githubusercontent.com/45623682/179844990-73762b2f-b2bb-4bf1-8f51-79bc6eb0fe9d.png)

As seen in the screenshot the right side of the base (rcl 6) is being build "correctly" but there is 1 patch of extensions placed too early in room stage.

We need to write better base planning code

**Comment by CarsonBurke** [comment]
Perhaps baseCM, roadCM, and terrainCM are not being reset when other things are? I should try testing using visuals
